### ISSUE TITLE
Need to re-name the block from "my_courses"

### ISSUE THREAD

**Issue by upats** [UniversityofPortland/moodle-block_custom_course_menu#14]
There is already a block in the moodle plugins database named my_courses so we need to re-name this to something else before it can be submitted.

This will unfortunately require us to do DB changes which means we need to do some RENAME TABLE stuff.

**Comment by mudrd8mz** [comment]
Hmm. This is tricky. Firstly, there really is the block https://moodle.org/plugins/view/block_my_courses which seems quite orphaned by now, not actively maintained.

So your block will badly affect that other block's table and indexes if it happens to be installed, too. It might be better to probably start distributing block_custom_course_menu as a fresh new plugin without db/upgrade.php

**Comment by rachel-smith** [comment]
Upgrade.php removed on devel branch, will be removed on master when branches are merged. If University of Portland needs the upgrade.php, it will be located on the upgradebranch of this repository.

**Comment by rachel-smith** [comment]
Block has been renamed and upgrade.php removed, closing issue.
