### ISSUE TITLE
Inapproproate PARAM types defined

### ISSUE THREAD

**Issue by mudrd8mz** [UniversityofPortland/moodle-block_custom_course_menu#16]
`optional_param('categoryid', null, PARAM_NOTAGS)` for integer looks malicious. Plus, that variable does not seem to be used there in favorite.php.

**Comment by mudrd8mz** [comment]
In sort.php, you use `$ids = required_param('ids', PARAM_TEXT);` and then explode that to populate the list of (hopefully) integers. There is more safe and reliable way - look at `required_param_array()` and how `$DB->get_in_or_equal()` are to be used.

**Comment by rachel-smith** [comment]
Eliminated categoryid param in favorite.php since there is no use for it. Up to date currently on level branch. Working on comment #2 regarding required_param_array() and the use of $DB->get_in_or_equal()

**Comment by rachel-smith** [comment]
#24 Fixed issue with sort.php to use required_param_array() and get_in_or_equal().
