### ISSUE TITLE
The naming convention for the settings

### ISSUE THREAD

**Issue by mudrd8mz** [UniversityofPortland/moodle-block_custom_course_menu#17]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Settings-storage

Currently you store the settings into the global config settings table, which is discouraged for new plugins and is supported for legacy and backward-compatibility reasons only.

**Comment by rachel-smith** [comment]
Fixed on "devel" branch. Switched naming convention from plugintype_puginname_settingname to plugintype_pluginname/settingname in settings.php file so settings are stored in config_plugins table, not the main config table.

**Comment by rachel-smith** [comment]
Update: This causes bug where last viewed courses no longer show up, looking into the issue.

**Comment by rachel-smith** [comment]
Update: Error is in interface.php in sql query to DB, neet to use get_config(). Still working on issue.

**Comment by rachel-smith** [comment]
Update: Fixed for "last # viewed", working to fix "favorite" in a similar way. Note: Use get_config(block_custom_course_menu_enablelastviewed) instead of $CFG->config_enablelastviewed.

**Comment by rachel-smith** [comment]
Update: Fixed for favorites as well. Issue seems to be resolved, closing issue.
