### ISSUE TITLE
New 3.3+ version to attempt to get into Moodle plugin database

### ISSUE THREAD

**Issue by Syxton** [UniversityofPortland/moodle-block_custom_course_menu#39]
@UniversityofPortland/contributors 

I have created a new branch called 33+ and have tested it with moodle 3.4 and the latest 3.5dev releases.  Let's try to get this into the plugin database.

If you want, I could try to get this done.

**Comment by upats** [comment]
@Syxton That would be awesome if you are willing to get this new version into the plugin database. Can you send me your moodle.org username so I can add you as a maintainer to the plugin?

**Comment by Syxton** [comment]
@upats

**Comment by Syxton** [comment]
@upats davidso1@rose-hulman.edu
